require("battle.UITouchButton")
require("battle.SummonBtn")
require("battle.BattleScene")
require("battle.Player")
require("battle.Soldier")
require("battle.Enemy")
require("battle.Bunker")
require("battle.SoldierClose")